# Default LLM Configuration
default_model: "gemini"
max_tokens: 8292

# Supported file types
supported_file_types:
  - ".md"
  - ".mdx"
  - ".rst"
  - ".rstx"
  - ".py"
  - ".html"
  - ".ipynb"

# LLM Provider Configurations
llm_configs:
  gemini:
    temperature: 0.3
  cohere:
    temperature: 0.3
  groq:
    temperature: 0.3
  together:
    temperature: 0.3

# Directory Configuration
input_directory: "input_files"
output_directory: "output_files"

# Translation Settings
translated_output_directory: "translated_files"
